export const ROUND_DURATION_SECONDS = 30;
export const ROUND_DURATION_MS = ROUND_DURATION_SECONDS * 1000;

export const VALIDATION_DURATION_SECONDS = 20;
export const VALIDATION_DURATION_MS = VALIDATION_DURATION_SECONDS * 1000;

export const MAX_ROUNDS = 2;
