
import fs from 'fs';
import path from 'path';

const ICONS_DIR = path.join(process.cwd(), 'public/assets/icons');
const OUTPUT_FILE = path.join(process.cwd(), 'src/types/pixel-icons.ts');

function generateIconTypes() {
  try {
    // Check if icons directory exists
    if (!fs.existsSync(ICONS_DIR)) {
      console.error(`Icons directory not found: ${ICONS_DIR}`);
      process.exit(1);
    }

    // Read files
    const files = fs.readdirSync(ICONS_DIR);
    
    // Filter SVG files and remove extension
    const icons = files
      .filter(file => file.endsWith('.svg'))
      .map(file => file.replace('.svg', ''));

    // Generate type definition
    const typeDefinition = `// This file is auto-generated by scripts/generate-icon-types.ts
// Do not edit this file manually

export type PixelIconName =
${icons.map(icon => `  | "${icon}"`).join('\n')};
`;

    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(OUTPUT_FILE, typeDefinition);
    
    console.log(`Successfully generated ${icons.length} icon types in ${OUTPUT_FILE}`);
    
  } catch (error) {
    console.error('Error generating icon types:', error);
    process.exit(1);
  }
}

generateIconTypes();
